<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net9.0</TargetFramework>
		<LangVersion>latest</LangVersion>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="JetBrains.Annotations" Version="2024.3.0" />
		<PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.13.0" />
		<PackageReference Include="MSTest" Version="3.8.3" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\DUMPSYM\DUMPSYM.csproj" />
	</ItemGroup>

	<ItemGroup>
		<Using Include="Microsoft.VisualStudio.TestTools.UnitTesting" />
	</ItemGroup>

	<ItemGroup>
	  <Compile Update="UnitTestAuto.g.cs">
	    <DependentUpon>UnitTestAuto.tt</DependentUpon>
	    <DesignTime>True</DesignTime>
	    <AutoGen>True</AutoGen>
	  </Compile>
	</ItemGroup>

	<ItemGroup>
		<None Update=".SYM file list.txt">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="UnitTestAuto.tt">
		  <LastGenOutput>UnitTestAuto.g.cs</LastGenOutput>
		  <Generator>TextTemplatingFileGenerator</Generator>
		</None>
	</ItemGroup>

	<ItemGroup>
	  <Service Include="{508349b6-6b84-4df5-91f0-309beebad82d}" />
	</ItemGroup>

</Project>